<footer class="footer">
	<div class="container">
		<p class="text-muted"><?php $copyright ?> All rights reserved &copy <?php date('Y') ?></p>
	</div>
</footer>

<script>window.jQuery || document.write('<script src="frontend/view/theme/default/assets/js/jquery.min.js"><\/script>')</script>
<script src='frontend/view/theme/default/assets/js/bootstrap.min.js'></script>
<script src='frontend/view/theme/default/assets/js/ie10-viewport-bug-workaround.js'></script>
</body>
</html>