<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="">
	<title><?php echo $website_name ?></title>

	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/bootstrap.min.css'>
	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/bootstrap-theme.min.css'>
	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/ie10-viewport-bug-workaround.css'>
	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/ie10-viewport-bug-workaround.css'>
	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/custom.css'>
	<link rel='stylesheet' href='frontend/view/theme/default/assets/css/colorbox/colorbox.css'>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="frontend/view/theme/default/assets/js/jquery.colorbox-min.js"></script>

	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

  <body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><?php echo $website_name ?></a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<?php if (isset($navs) && !empty($navs)) { ?>
				<?php foreach ($navs as $nav) { ?>
					<?php if (empty($nav['children'])) { ?>
					<li><a href="<?php echo $nav['url'] ?>"><?php echo $nav['name'] ?></a></li>
					<?php } else { ?>
					<li class="dropdown">
					  <a href="<?php echo $nav['url'] ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $nav['name'] ?><span class="caret"></span></a>
					  <ul class="dropdown-menu">
					  	<?php foreach ($nav['children'] as $child) { ?>
						<li><a href="<?php echo $child['url'] ?>"><?php echo $child['name'] ?></a></li>
						<?php } ?>
					  </ul>
					</li>
					<?php } ?>
				<?php } ?>
				<?php } ?>
		  </ul>
		</div>
	  </div>
	</nav>
