<?php echo $header ?>
<div class="container">
	<div id="carousel-generic" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
		  <li data-target="#carousel-generic" data-slide-to="0" class="active"></li>
		  <li data-target="#carousel-generic" data-slide-to="1"></li>
		  <li data-target="#carousel-generic" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="/images/slider/Yellowstone-Teton-Elk-Sunset.jpg" alt="Yellowstone Teton Elk Sunset">
			</div>
			<div class="item">
				<img src="/images/slider/Yellowstone-Teton-Elk-Sunset.jpg" alt="Yellowstone Teton Elk Sunset">
			</div>
			<div class="item">
				<img src="/images/slider/Yellowstone-Teton-Elk-Sunset.jpg" alt="Yellowstone Teton Elk Sunset">
			</div>
		</div>
		<a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
</div>

<div class="container margin-top-20">
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img src="/images/homepage/ice.jpg" alt="bear">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Thumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail label</p>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img src="/images/homepage/lake.jpg" alt="bear">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Thumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail label</p>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img src="/images/homepage/desert.jpg" alt="bear">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Thumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail labelThumbnail label</p>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $footer ?>