<ul id="menu">
	<li id="dashboard"><a href="<?php echo $home; ?>"><i class="fa fa-dashboard fa-fw"></i> <span><?php echo $text_dashboard; ?></span></a></li>
	<li id="catalog"><a class="parent"><i class="fa fa-tags fa-fw"></i> <span><?php echo $text_catalog; ?></span></a>
		<ul>
			<li><a href="<?php echo $category; ?>"><?php echo $text_category; ?></a></li>
			<li><a href="<?php echo $product; ?>"><?php echo $text_product; ?></a></li>
			<li><a href="<?php echo $page; ?>"><?php echo $text_page; ?></a></li>
		</ul>
	</li>
	<li id="nav"><a class="parent"><i class="fa fa-tags fa-fw"></i> <span><?php echo $text_nav_menu; ?></span></a>
		<ul>
			<li><a href="<?php echo $menu; ?>"><?php echo $text_menu; ?></a></li>
		</ul>
	</li>
	<li id="system"><a class="parent"><i class="fa fa-cog fa-fw"></i> <span><?php echo $text_system; ?></span></a>
		<ul>
			<li><a href="<?php echo $setting; ?>"><?php echo $text_setting; ?></a></li>
			<li><a class="parent"><?php echo $text_design; ?></a>
				<ul>
					<li><a href="<?php echo $layout; ?>"><?php echo $text_layout; ?></a></li>
				</ul>
			</li>
			<li><a class="parent"><?php echo $text_users; ?></a>
				<ul>
					<li><a href="<?php echo $user; ?>"><?php echo $text_user; ?></a></li>
					<li><a href="<?php echo $user_group; ?>"><?php echo $text_user_group; ?></a></li>
				</ul>
			</li>
			<li><a class="parent"><?php echo $text_localisation; ?></a>
				<ul>
					<li><a href="<?php echo $language; ?>"><?php echo $text_language; ?></a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li id="tools"><a class="parent"><i class="fa fa-wrench fa-fw"></i> <span><?php echo $text_tools; ?></span></a>
		<ul>
			<li><a href="<?php echo $error_log; ?>"><?php echo $text_error_log; ?></a></li>
		</ul>
	</li>
</ul>
