<?php echo $header; ?>
<div class="container margin-top-20">
	<h2>Contact Form</h2>
	<form method="post" target="" id="contact">
		<div class="form-group">
			<label for="name">Name:</label>
			<input type="name" class="form-control" id="name" placeholder="Your name" value="<?php echo $name ?>">
		</div>
		<div class="form-group">
			<label for="email">Email:</label>
			<input type="email" class="form-control" id="email" placeholder="Your email" value="<?php echo $email ?>">
		</div>
		<div class="form-group">
			<label for="telephone">Telephone:</label>
			<input type="telephone" class="form-control" id="telephone" placeholder="Your telephone" value="<?php echo $telephone ?>">
		</div>
		<div class="form-group">
			<label for="message">Message:</label>
			<textarea class="form-control" id="message" placeholder="Your message"><?php echo $message ?></textarea>
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
</div>
<?php echo $footer; ?> 